const API_URLS = {
  V1: {
    LOGIN: "/auth/sign-in",
    LOGOUT: "/auth/logout",
    FORGET_PASSWORD: "/v1/user-management/forget-password",
    RESET_PASSWORD: "/v1/user-management/reset-password",
    VIDEO_LIBRARY_LIST: "/api/v1/transcribe/content",
    VIDEO_LIBRARY_VIDEO_SCREENSHOTS: "/v1/library-management/screenshots",
    VIDEO_LIBRARY_VIDEO_EDIT: "/v1/library/update-editing-status",
    VIDEO_LIBRARY_VIDEO_DETAIL: "/v1/library/find-by-id/",
    S3_MULTIPART_GET_UPLOAD_ID: "/v1/library/s3multipart-upload/start-upload",
    S3_MULTIPART_GET_SIGNED_URL:
      "/v1/library/s3multipart-upload/get-signed-url",
    S3_MULTIPART_COMPLETE_UPLOAD:
      "/v1/library/s3multipart-upload/complete-upload",
    SAVE_VIDEO_DATA: "/v1/library/save-update-data",
    DELETE_VIDEO_DATA: "/v1/library-management/delete-media",
    PROPERTY_LIST: "/v1/property-management/property/list",
    TEMPLATE_LIST: "/v1/property-template-list",
    LIST_S3_VIDEOS: "/v1/library/list-s3-videos",
    UPDATE_S3_VIDEO_STATUS: "/v1/library/insert-s3-video-details", // SAVE_AS_DRAFT
    THUMBNAIL_LIST: "/v1/s3-thumbnail-images/list",
    DASHBOARD_GRAPHS: "/v1/dashboard-management/dashboard-analytics-graph",
    DASHBOARD_CARDS: "/v1/dashboard-management/dashboard-analytics",
    THUMBNAIL_UPDATE: "/v1/library-management/update-thumbnail",
    METADATA_UPDATE: "/v1/library-management/update-media-data",
    CATALOGUE_LIST: "/v1/catalogue-management/catalogue/list",
    SECTION_LIST: "/v1/section-management/section/list",
    RAW_VIDEO_FIND_BY_CONTENT_ID: "/v1/library/raw-video/find-by-content-id/", //from step 1 to 3
    MEDIA_VIDEO_FIND_BY_CONTENT_ID: "/v1/library/find-by-id/", // for step 4
    ADD_SUBTITLE: "/v1/library/upload-subtitle",
    DELETE_AUDIO_AND_SUBTITLE: "/v1/raw-video/delete-subtitle-audio",
    LANGUAGE_LIST: "/v1/language-management/language/list",
    SUBMIT_AND_TRANSCODE: "/v1/library/transcode-media/create-job",
    SAVE_DATA_TO_MEDIA_TABLE: "/v1/library/transcoding/raw-video-to-media",
    SAVE_USER_DATA: "/v1/user-management/add/insert-user",
    SAVE_PRODUCT_DATA: "/product/add",
    UPDATE_PRODUCT_DATA: "/product/",
    USER_LIST: "/v1/user-management/admin-user/list",
    PRODUCT_LIST: "/product/list",
    FIND_USER_BY_ID: "/v1/user-management/find-by-id/",
    FIND_PRODUCT_BY_ID: "/product/",
    DELETE_USER_DATA: "/v1/user-management/delete-adminuser",
    DELETE_PRODUCT_DATA: "/product",
    TEMPLATE_MASTER_LIST: "/v1/template-management/template/list",
    FIND_TEMPLATE_BY_ID: "/v1/template-management/find-by-id",
    DELETE_TEMPLATE_DATA: "/v1/template-management/delete-template",
    SAVE_TEMPLATE_DATA: "/v1/template-management/save-update-data",
    TEMPLATE_BUMPER_GET_UPLOAD_ID:
      "/v1/template-management/add-update-template/start-upload",
    TEMPLATE_BUMPER_GET_SIGNED_URL:
      "/v1/template-management/add-update-template/get-signed-url",
    TEMPLATE_BUMPER_COMPLETE_UPLOAD:
      "/v1/template-management/add-update-template/complete-upload",
    RECENT_ACTIVITY: "/v1/recent-activity/list",
    NOTIFICATION_LIST: "/v1/notification/list",
    CLEAR_ALL_NOTIFICATIONS: "/v1/notification/clear-notification",
    CHANGE_PASSWORD: "/v1/user-management/change-password",
    CLONE_VIDEO_RECORD: "/v1/library-management/clone-record",
    SAVE_AS_DRAFT_OR_TRANSCODE: "/v1/library/save-draft-or-transcode-media",
    SCHEDULE_PUSH: "/v1/library-management/schedule-push",
    TRIM_LIVE_VIDEO: "/v1/harvest",
    PROPERTY_MASTER_LIST: "/v1/property-management/property/list-property",
    PROPERTY_MASTER_LIST_ONE: "/v1/property-management/property/list-one",
    PROPERTY_MASTER_SAVE_UPDATE: "/v1/property-management/property",
    UPDATE_VIDEO_STATUS: "/v1/library/change-status/",
    SAVE_VIDEO_DETAILS: "/v1/library/video-details",
    GET_PRESIGNED_URL: "/api/v1/transcribe/upload",
    TRANSCRIBE_CONTENT: "/api/v1/transcribe",
    UPDATE_VTT_FILE: "/api/v1/transcribe/content/update-vtt/",
    TRANSCODE_VIDEO: "/api/v1/transcribe/content/transcode/",
  },
};

export default API_URLS;
